### ISSUE TITLE
Not working on Xcode11b3

### ISSUE THREAD

**Issue by tarunon** [tarunon/XCTAssertAutolayout#7]
https://github.com/tarunon/XCTAssertAutolayout/blob/master/Sources/XCTAssertAutolayout/Core/CFunctionInjector.swift#L34-L36

It returns very large pointer, seems change UIKit linking as dynamic.
It make can't hook using jmp instruction.
Require to use other hooking way, maybe push/ret can work.

**Comment by inamiy** [comment]
acbe29f Confirmed it's working both on Xcode 10 and 11 beta 3 🎉

**Comment by tarunon** [comment]
I will

**Comment by omochi** [comment]
おもしろいね
